name: pangenome-hgt-sim
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.12
  - msprime=1.3.1
  - scipy=1.12.0
  - seaborn=0.12.2
  - matplotlib=3.9.2
  - pandas
  - numpy
  - numba
  - statsmodels=0.14.4
  - tskit
  - daiquiri=3.0.0
  - ipykernel
  - tqdm=4.66.1
  - networkx
  - pygraphviz
  - lxml
  - graphviz
  - pyqt
  - pyside6
  - scikit-learn
  - pip
  - pip:
      - statsmodels==0.14.4
      - bintrees==2.2.0
      - newick==1.9.0
      - tskit-arg-visualizer==0.0.1
      - sbi==0.23.2
      - pytensor
      - pymc
      - torch
      - torch-geometric
      - nflows
      - zuko
      - ete3
      - cons
      - pyvis
      - jupyterlab
      - ipywidgets
      - notebook
      - xarray
      - arviz
