name: pangenome-hgt-sim

channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - msprime=1.3.1
  - matplotlib[version='>=3.4.0']
  - scipy=1.12.0
  - seaborn=0.12.2
  - python==3.12.1
  - daiquiri=3.0.0
  - ipykernel
  - tqdm=4.66.1
  - pip=23.3.1
  - pip:
      - bintrees==2.2.0
      - newick==1.9.0
      - tskit-arg-visualizer==0.0.1